spring:
  application:
    name: jsonWebToken
  datasource:
    url: jdbc:postgresql://127.0.01/Learn
    username: postgres
    password: new_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


